title: Ethan Parks
logo: /assets/img/IMG_5486.jpg
description: Applied ML & NLP · Data Science MS · Mountain Athlete
theme: jekyll-theme-minimal

#To render code correctly
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

#For adding new links to site
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /medVec/
    url: /geomTransformer/
